#!/usr/bin/python
import subprocess

from deployer.config import ConfigStack
from jujuclient import Environment
import utils

parser = utils.juju_arg_parser(
    description="""Parse/merge the provided deployer configs and set every value on all services""",
)

# same args as deployer
parser.add_argument(
    '-c', '--config',
    help=('File containing deployment(s) json config. This '
          'option can be repeated, with later files overriding '
          'values in earlier ones.'),
    dest='configs', action='append')
parser.add_argument(
    '--series', type=str,
    help=('Override distro series in config files'),
    dest='series', default=None)

parser.add_argument("deployment", nargs="?")
options = parser.parse_args()

config = ConfigStack(options.configs, options.series)

env_name = subprocess.check_output(['juju', 'switch']).strip()
env = Environment.connect(env_name)

for name, svc in config.data[options.deployment]['services'].items():
    if 'options' in svc:
        print('Setting config for service {}'.format(name))
        env.set_config(name, svc['options'])
